name: Sopan Reports Automation

# Trigger workflow manually or daily at 8 AM IST
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # UTC 2 AM = IST 7:30 AM

jobs:
  download-reports:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Install dependencies (works without package-lock.json)
      - name: Install dependencies
        run: |
          npm install

      # 4️⃣ Create downloads folder (for CSV)
      - name: Create downloads folder
        run: mkdir -p downloads

      # 5️⃣ Run Puppeteer script
      - name: Run Sopan Reports Script
        run: node index.js

      # 6️⃣ Upload CSV as artifact
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: sopan-csv
          path: downloads/
